name: AllAPILoader
main: BeckenPlayZMCPE\AllAPILoader\Main
version: 1.0.0
api:
- 3.2.3
- 3.2.0
- 3.3.0
- 4.0.0
author: BeckenPlayZMCPE
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
